"""
Email parser for LegalMail RAG.

Parses the structured .txt email files generated by data_cleaning.py
and extracts rich metadata for downstream indexing.

Expected file format:
    De: Name <email>
    Para: Name <email>
    Fecha: YYYY-MM-DD HH:MM:SS
    Adjuntos: file1.docx, file2.pdf
     
    Asunto: RE: Subject line
    Cuerpo:
    Body text...
"""
from __future__ import annotations

import re
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from langchain_core.documents import Document
from loguru import logger


# ── Regex patterns for header extraction ─────────────────────────────────────

_RE_FROM = re.compile(r"^De:\s*(.+)$", re.MULTILINE)
_RE_TO = re.compile(r"^Para:\s*(.+)$", re.MULTILINE)
_RE_DATE = re.compile(r"^Fecha:\s*(.+)$", re.MULTILINE)
_RE_ATTACHMENTS = re.compile(r"^Adjuntos:\s*(.+)$", re.MULTILINE)
_RE_SUBJECT = re.compile(r"^Asunto:\s*(.+)$", re.MULTILINE)

# Extract name and email from "Name <email>" format
_RE_NAME_EMAIL = re.compile(r"^(.+?)\s*<(.+?)>\s*$")

# Detect reply / forward prefixes in subject line
_RE_REPLY_PREFIX = re.compile(r"^(?:RE|Re|RV|Rv|FWD|Fwd|FW|Fw):\s*", re.IGNORECASE)


class EmailParser:
    """Parse structured email .txt files into LangChain Documents with rich metadata."""

    def parse_file(self, file_path: str | Path) -> List[Document]:
        """Parse a single email file and return a list with one Document.

        Args:
            file_path: Path to the .txt email file.

        Returns:
            List containing a single Document with:
              - page_content = email body
              - metadata = structured fields (from_name, from_email, date, etc.)
        """
        path = Path(file_path)
        if not path.exists():
            raise FileNotFoundError(f"Email file not found: {file_path}")

        text = path.read_text(encoding="utf-8")
        metadata = self._extract_metadata(text, path)
        body = self._extract_body(text)

        doc = Document(
            page_content=body,
            metadata=metadata,
        )
        logger.debug(f"Parsed email: {path.name} → {metadata.get('subject', '?')}")
        return [doc]

    def parse_directory(
        self, dir_path: str | Path, pattern: str = "*.txt"
    ) -> List[Document]:
        """Parse all email files in a directory.

        Args:
            dir_path: Directory containing .txt email files.
            pattern: Glob pattern to match files.

        Returns:
            List of Documents, one per email file.
        """
        path = Path(dir_path)
        if not path.is_dir():
            raise NotADirectoryError(f"Not a directory: {dir_path}")

        documents: List[Document] = []
        for email_file in sorted(path.glob(pattern)):
            try:
                documents.extend(self.parse_file(email_file))
            except Exception as exc:
                logger.error(f"Failed to parse '{email_file.name}': {exc}")

        logger.info(f"Parsed {len(documents)} email(s) from '{path}'")
        return documents

    # ──────────────────────────────────────────────────────────────────────
    # Internal helpers
    # ──────────────────────────────────────────────────────────────────────

    def _extract_metadata(self, raw_text: str, file_path: Path) -> Dict[str, Any]:
        """Extract all structured metadata from the email text."""
        meta: Dict[str, Any] = {
            "source": str(file_path),
            "filename": file_path.name,
            "file_type": "email",
        }

        # ── From ─────────────────────────────────────────────────────────
        from_match = _RE_FROM.search(raw_text)
        if from_match:
            name, email = self._parse_name_email(from_match.group(1))
            meta["from_name"] = name
            meta["from_email"] = email

        # ── To ───────────────────────────────────────────────────────────
        to_match = _RE_TO.search(raw_text)
        if to_match:
            name, email = self._parse_name_email(to_match.group(1))
            meta["to_name"] = name
            meta["to_email"] = email

        # ── Date ─────────────────────────────────────────────────────────
        date_match = _RE_DATE.search(raw_text)
        if date_match:
            date_str = date_match.group(1).strip()
            meta["date_raw"] = date_str
            parsed_date = self._parse_date(date_str)
            if parsed_date:
                meta["date"] = parsed_date.strftime("%Y-%m-%d")
                meta["date_iso"] = parsed_date.isoformat()
                meta["year"] = parsed_date.year
                meta["month"] = parsed_date.month
                meta["day"] = parsed_date.day

        # ── Attachments ──────────────────────────────────────────────────
        attach_match = _RE_ATTACHMENTS.search(raw_text)
        if attach_match:
            raw_attachments = attach_match.group(1).strip()
            if raw_attachments and raw_attachments.lower() not in ("", "ninguno", "none", "nan"):
                meta["attachments"] = raw_attachments
                meta["attachment_list"] = [
                    a.strip() for a in raw_attachments.split(",") if a.strip()
                ]
                meta["has_attachments"] = True
            else:
                meta["has_attachments"] = False
        else:
            meta["has_attachments"] = False

        # ── Subject ──────────────────────────────────────────────────────
        subject_match = _RE_SUBJECT.search(raw_text)
        if subject_match:
            full_subject = subject_match.group(1).strip()
            meta["subject"] = full_subject

            # Clean subject (remove RE:/FWD: prefixes) for thread detection
            clean_subject = _RE_REPLY_PREFIX.sub("", full_subject).strip()
            meta["subject_clean"] = clean_subject

            # Thread ID derived from cleaned subject
            meta["thread_id"] = self._generate_thread_id(clean_subject)

            # Detect if reply or forward
            meta["is_reply"] = bool(_RE_REPLY_PREFIX.match(full_subject))

        return meta

    def _extract_body(self, raw_text: str) -> str:
        """Extract the email body (everything after 'Cuerpo:')."""
        marker = "Cuerpo:"
        idx = raw_text.find(marker)
        if idx == -1:
            # Fallback: return everything after the blank line separating headers
            parts = raw_text.split("\n\n", 1)
            return parts[1].strip() if len(parts) > 1 else raw_text.strip()
        return raw_text[idx + len(marker) :].strip()

    @staticmethod
    def _parse_name_email(raw: str) -> tuple[str, str]:
        """Parse 'D. Jaime Cortés Villanueva <j.cortes@law.com>' into (name, email)."""
        match = _RE_NAME_EMAIL.match(raw.strip())
        if match:
            return match.group(1).strip(), match.group(2).strip()
        # Fallback: entire string as name, empty email
        return raw.strip(), ""

    @staticmethod
    def _parse_date(date_str: str) -> Optional[datetime]:
        """Try multiple date formats to parse the date string."""
        formats = [
            "%Y-%m-%d %H:%M:%S",
            "%Y-%m-%d %H:%M",
            "%Y-%m-%d",
            "%d/%m/%Y %H:%M:%S",
            "%d/%m/%Y",
        ]
        for fmt in formats:
            try:
                return datetime.strptime(date_str.strip(), fmt)
            except ValueError:
                continue
        logger.warning(f"Could not parse date: '{date_str}'")
        return None

    @staticmethod
    def _generate_thread_id(clean_subject: str) -> str:
        """Generate a normalised thread ID from the cleaned subject line.

        Example:
            'Proyecto Ámbar — Due Diligence — Preguntas sobre contencioso'
            → 'proyecto_ambar_due_diligence_preguntas_sobre_contencioso'
        """
        # Normalise unicode (remove accents)
        nfkd = unicodedata.normalize("NFKD", clean_subject)
        ascii_text = nfkd.encode("ascii", "ignore").decode("ascii")

        # Lowercase, replace separators with spaces, then underscores
        cleaned = ascii_text.lower()
        cleaned = re.sub(r"[—–\-/\\|:;,\.]", " ", cleaned)
        cleaned = re.sub(r"[^a-z0-9\s]", "", cleaned)
        cleaned = re.sub(r"\s+", "_", cleaned.strip())

        return cleaned
